server:
  port: 8761

spring:
  application:
    name: eureka-server
  cloud:
    uri: http://127.0.0.1:8888
    name: jimart
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false